language: python
before_install:
    - pip install --upgrade pytest
    - python --version
    - pip    --version
    - pytest --version
    - pip install pytest-cov
    - pip install codecov
script:
    - PYTHONPATH=. pytest --cov-report term --cov=sym_lis
    - PYTHONPATH=. pytest --cov-report term --cov=sym_repl     --cov-append
    - PYTHONPATH=. pytest --cov-report term --cov=plugin_shell --cov-append
after_success:
    - codecov
